#ifndef COFFEE_APP_CONFIG_H
#define COFFEE_APP_CONFIG_H

#ifndef COFFEE_DEFAULT_WIDTH
#define COFFEE_DEFAULT_WIDTH 800
#endif

#ifndef COFFEE_DEFAULT_HEIGHT
#define COFFEE_DEFAULT_HEIGHT 480
#endif

#define COFFEE_SPLASH_MS 1000U
#define COFFEE_COMPLETION_MS 2200U
#define COFFEE_CANCELLED_MS 1500U
#define COFFEE_TICK_MS 5U

#endif
